[settings]
cache_prune_age = "7d"

[tools]
# Programming Languages
node = "latest"
bun = "latest"
npm = "latest"
pnpm = "latest"
python = "latest"
java = { version = "openjdk-17" }
go = "latest"
opam = "latest"
rust = "latest"
zig = "latest"

# Utilities
1password = "latest"
dua = "latest"
eza = "latest"
tmux = "latest"
ripgrep = "latest"
neovim = "latest"
fastfetch = "latest"
fzf = "latest"
zoxide = "latest"
